/**
 * Auto-generated migration map for authenticator-app
 * Maps old API function names to generated @autional/shared/generated/api
 * Generated by: python scripts/generate_api_ts.py --migration authenticator-app
 */

import * as Generated from '@autional/shared/generated/api';

export const getCurrentUser = Generated.authMe;
export const getMfaStatus = Generated.mfaStatusByStatus;
export const enableTotp = Generated.mfaTotpEnablePost;
export const verifyTotpSetup = Generated.mfaTotpVerifyPost;
export const disableTotp = Generated.mfaTotpDisablePost;
export const validateTotpCode = Generated.mfaTotpValidatePost;
export const generateBackupCodes = Generated.mfaBackupCodesGeneratePost;
export const getPushHistory = Generated.mfaPushHistory;
export const getAuthenticatorDevices = Generated.authMeAuthenticatorDevices;
export const getCloudBackups = Generated.authMeAuthenticatorBackup;
export const uploadCloudBackup = Generated.authMeAuthenticatorBackupPost;
export const deleteCloudBackup = Generated.authMeAuthenticatorBackupByBackupDelete;
export const getDeviceSyncList = Generated.mfaDevicesSync;
export const syncDevice = Generated.mfaDevicesSyncPost;
